### ISSUE TITLE
Permissões insuficientes 

### ISSUE THREAD

**Issue by brudarko** [jpmoura/sire-icea-ufop#3]
O professor titular da reserva pode desalocar sua reserva ou somente o administrador? Não sei se se encaixa como bug ou feature request.

![screen shot 2017-12-21 at 13 02 37](https://user-images.githubusercontent.com/25669568/34261197-8c1fb17e-e64f-11e7-9f4e-f542be9eca79.png)
![screen shot 2017-12-21 at 13 05 09](https://user-images.githubusercontent.com/25669568/34261219-9de414a4-e64f-11e7-92ba-0127d956b824.png)

**Comment by jpmoura** [comment]
Isso é um bug resultante da adaptação. Somente o autor da reserva e o administrador tem permissão para desalocar uma determinada reserva e somente ambos podem visualizar o botão correspondente dessa ação.

Isso foi corrigido nos commits https://github.com/jpmoura/sire/commit/0d22592d187aa7d72c2501d1fccaeb0da0019e58 e https://github.com/jpmoura/sire/commit/a21d93b17f4bc22abe1c791ee70e7cac9d906c81
