### ISSUE TITLE
Reservas feitas, porém, na dashboard não existem

### ISSUE THREAD

**Issue by brudarko** [jpmoura/sire-icea-ufop#4]
Na dashboard ela reconhece como se não houvessem reservas (no caso, minhas próximas reservas)

![screen shot 2017-12-21 at 18 43 32](https://user-images.githubusercontent.com/25669568/34274317-318633e8-e67f-11e7-9911-09e3c7fe99d5.png)
![screen shot 2017-12-21 at 18 43 48](https://user-images.githubusercontent.com/25669568/34274318-31d75bba-e67f-11e7-8a56-91f65c8d8397.png)

**Comment by jpmoura** [comment]
Corrigido no commit 47dcd3bcc8105bf6021047f5391f7d42dbf827b9
