### ISSUE TITLE
[Feature Request] Habilidade de definir os horários

### ISSUE THREAD

**Issue by brudarko** [jpmoura/sire-icea-ufop#5]
Por exemplo, minha escola no horário matutino começa as 7:45 e as aulas são de 45 minutos cada, possuindo um intervalo das 10:00 as 10:15, além disso, a noite, são duas aulas e depois o recreio (ao contrário dos períodos da manhã e tarde.

Desde já, agradecido.
Att, Frank.

**Comment by jpmoura** [comment]
Você pode fazer isso com usuário do tipo administrador, editando as regras. No menu ```Visualizar Regras``` você é capaz de ver todas as regras do negócio e ao final da página existe o botão para editar.
