### ISSUE TITLE
Erro durante configuração inicial

### ISSUE THREAD

**Issue by CosmeLorim** [jpmoura/sire-icea-ufop#7]
Durante a instalação, da branche generico, ao executar o comando
`php artisan migrate`

Retorna o seguinte erro
```
  [PDOException]         
  could not find driver 
```

**Comment by jpmoura** [comment]
Esse erro está relacionado com as extensões PHP do Banco de Dados que você está utilizando @CosmeLorim, você vai precisar instalar as extensões relacionadas para que funcione corretamente.
